// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $container;
    $('.disable-anchors a').click(function(e) {
      e.preventDefault();
    });
    $('[data-href]').click(function(e) {
      console.log($(this).data('href'));
      document.location.replace($(this).data('href'));
    });
    $('.site-menu .top').click(function(e) {
      e.preventDefault();
      $('.site-wrapper').toggleClass('menu-on');
    });
    $container = $('.isotope-grid');
    $container.children('li').addClass('isotope-item');
    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'fitRows'
      });
    });
  });

}).call(this);
